name: Build and Deploy HTML to Azure Web App

on:
  push:
    branches:
      - feat/fukaor  # デプロイをトリガーするブランチを指定

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Hello World HTML
      run: |
        echo "<!DOCTYPE html><html><head><title>Hello</title></head><body><h1>Hello, world</h1></body></html>" > index.html

    - name: Zip the HTML file
      run: |
        zip build.zip index.html

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ekkyowebapp-github-actions-linux
        resource-group: ekkyoResourceGroup
        package: build.zip
        startup-command: 'pm2 serve /home/site/wwwroot --no-daemon'