name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのクローン
    - name: Checkout code
      uses: actions/checkout@v3

    # Azure CLIのセットアップ
    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v3

    # Azure Web Appへのデプロイ
    - name: Deploy to Azure Web App
      run: |
        az webapp up --name ekkyowebapp --resource-group ekkyoResourceGroup --location japaneast
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
