name: Build and Deploy HTML to Azure Web App

on:
  push:
    branches:
      - feat/react  # デプロイをトリガーするブランチを指定
      - feat/kurokomes
      - feat/ono
      - feat/fukaos 
      - main  # 本番環境用のブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
      RESOURCE_GROUP: ekkyoResourceGroup
      LOCATION: westus
      NODE_VERSION: '16'
      APP_SERVICE_PLAN: ekkyowebAppServicePlanLinux  # 固定のApp Serviceプラン

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd react-ekkyo-app
        npm install

    - name: Build the app
      run: |
        cd react-ekkyo-app
        npm run build

    - name: Zip the build directory
      run: |
        cd react-ekkyo-app/build
        zip -r ../build.zip .

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Web App if it does not exist
      run: |
        if ! az webapp show --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}; then
          az webapp create --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.APP_SERVICE_PLAN }} --name ${{ env.APP_NAME }} --runtime "NODE|16-lts"
        fi

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: react-ekkyo-app/build.zip
        startup-command: 'pm2 serve /home/site/wwwroot --no-daemon'