name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのクローン
    - name: Checkout code
      uses: actions/checkout@v3

    # Azureへのログイン
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Webアプリのデプロイ
    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config --name ekkyowebapp-github-actions-linux --resource-group ekkyoResourceGroup --repo-url https://github.com/${{ github.repository }} --branch main --manual-integration